// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: containers.proto
// Protobuf C++ Version: 6.33.1

#ifndef containers_2eproto_2epb_2eh
#define containers_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_containers_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_containers_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_containers_2eproto;
}  // extern "C"
namespace transport {
enum ExecTransType : int;
extern const uint32_t ExecTransType_internal_data_[];
enum ExecTypeOrOrderStatus : int;
extern const uint32_t ExecTypeOrOrderStatus_internal_data_[];
enum OrderType : int;
extern const uint32_t OrderType_internal_data_[];
enum Side : int;
extern const uint32_t Side_internal_data_[];
enum TimeInForce : int;
extern const uint32_t TimeInForce_internal_data_[];
class CancelOrderRequestContainer;
struct CancelOrderRequestContainerDefaultTypeInternal;
extern CancelOrderRequestContainerDefaultTypeInternal _CancelOrderRequestContainer_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CancelOrderRequestContainer_class_data_;
class ExecutionReportContainer;
struct ExecutionReportContainerDefaultTypeInternal;
extern ExecutionReportContainerDefaultTypeInternal _ExecutionReportContainer_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ExecutionReportContainer_class_data_;
class NewOrderSingleContainer;
struct NewOrderSingleContainerDefaultTypeInternal;
extern NewOrderSingleContainerDefaultTypeInternal _NewOrderSingleContainer_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull NewOrderSingleContainer_class_data_;
}  // namespace transport
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::transport::ExecTransType_internal_data_>
    internal::EnumTraitsImpl::value<::transport::ExecTransType>;
template <>
internal::EnumTraitsT<::transport::ExecTypeOrOrderStatus_internal_data_>
    internal::EnumTraitsImpl::value<::transport::ExecTypeOrOrderStatus>;
template <>
internal::EnumTraitsT<::transport::OrderType_internal_data_>
    internal::EnumTraitsImpl::value<::transport::OrderType>;
template <>
internal::EnumTraitsT<::transport::Side_internal_data_>
    internal::EnumTraitsImpl::value<::transport::Side>;
template <>
internal::EnumTraitsT<::transport::TimeInForce_internal_data_>
    internal::EnumTraitsImpl::value<::transport::TimeInForce>;
}  // namespace protobuf
}  // namespace google

namespace transport {
enum OrderType : int {
  ORDER_TYPE_UNSPECIFIED = 0,
  ORDER_TYPE_LIMIT = 1,
  ORDER_TYPE_MARKET = 2,
  OrderType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  OrderType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t OrderType_internal_data_[];
inline constexpr OrderType OrderType_MIN =
    static_cast<OrderType>(0);
inline constexpr OrderType OrderType_MAX =
    static_cast<OrderType>(2);
inline bool OrderType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int OrderType_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL OrderType_descriptor();
template <typename T>
::absl::string_view OrderType_Name(T value) {
  static_assert(::std::is_same<T, OrderType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to OrderType_Name().");
  return OrderType_Name(static_cast<OrderType>(value));
}
template <>
inline ::absl::string_view OrderType_Name(OrderType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<OrderType_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool OrderType_Parse(
    ::absl::string_view name, OrderType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<OrderType>(OrderType_descriptor(), name,
                                           value);
}
enum Side : int {
  SIDE_UNSPECIFIED = 0,
  SIDE_BID = 1,
  SIDE_ASK = 2,
  Side_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Side_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Side_internal_data_[];
inline constexpr Side Side_MIN =
    static_cast<Side>(0);
inline constexpr Side Side_MAX =
    static_cast<Side>(2);
inline bool Side_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int Side_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Side_descriptor();
template <typename T>
::absl::string_view Side_Name(T value) {
  static_assert(::std::is_same<T, Side>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Side_Name().");
  return Side_Name(static_cast<Side>(value));
}
template <>
inline ::absl::string_view Side_Name(Side value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Side_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool Side_Parse(
    ::absl::string_view name, Side* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Side>(Side_descriptor(), name,
                                           value);
}
enum TimeInForce : int {
  TIF_UNSPECIFIED = 0,
  TIF_DAY = 1,
  TimeInForce_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  TimeInForce_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t TimeInForce_internal_data_[];
inline constexpr TimeInForce TimeInForce_MIN =
    static_cast<TimeInForce>(0);
inline constexpr TimeInForce TimeInForce_MAX =
    static_cast<TimeInForce>(1);
inline bool TimeInForce_IsValid(int value) {
  return 0 <= value && value <= 1;
}
inline constexpr int TimeInForce_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL TimeInForce_descriptor();
template <typename T>
::absl::string_view TimeInForce_Name(T value) {
  static_assert(::std::is_same<T, TimeInForce>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to TimeInForce_Name().");
  return TimeInForce_Name(static_cast<TimeInForce>(value));
}
template <>
inline ::absl::string_view TimeInForce_Name(TimeInForce value) {
  return ::google::protobuf::internal::NameOfDenseEnum<TimeInForce_descriptor, 0, 1>(
      static_cast<int>(value));
}
inline bool TimeInForce_Parse(
    ::absl::string_view name, TimeInForce* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<TimeInForce>(TimeInForce_descriptor(), name,
                                           value);
}
enum ExecTransType : int {
  EXEC_TRANS_TYPE_UNSPECIFIED = 0,
  EXEC_TRANS_NEW = 1,
  EXEC_TRANS_CANCEL = 2,
  EXEC_TRANS_CORRECT = 3,
  EXEC_TRANS_STATUS = 4,
  ExecTransType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  ExecTransType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t ExecTransType_internal_data_[];
inline constexpr ExecTransType ExecTransType_MIN =
    static_cast<ExecTransType>(0);
inline constexpr ExecTransType ExecTransType_MAX =
    static_cast<ExecTransType>(4);
inline bool ExecTransType_IsValid(int value) {
  return 0 <= value && value <= 4;
}
inline constexpr int ExecTransType_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ExecTransType_descriptor();
template <typename T>
::absl::string_view ExecTransType_Name(T value) {
  static_assert(::std::is_same<T, ExecTransType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ExecTransType_Name().");
  return ExecTransType_Name(static_cast<ExecTransType>(value));
}
template <>
inline ::absl::string_view ExecTransType_Name(ExecTransType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ExecTransType_descriptor, 0, 4>(
      static_cast<int>(value));
}
inline bool ExecTransType_Parse(
    ::absl::string_view name, ExecTransType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<ExecTransType>(ExecTransType_descriptor(), name,
                                           value);
}
enum ExecTypeOrOrderStatus : int {
  EXEC_TYPE_OR_ORDER_STATUS_UNSPECIFIED = 0,
  STATUS_NEW = 1,
  STATUS_PARTIALLY_FILLED = 2,
  STATUS_FILLED = 3,
  STATUS_CANCELED = 4,
  STATUS_PENDING_CANCEL = 5,
  STATUS_REJECTED = 6,
  ExecTypeOrOrderStatus_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  ExecTypeOrOrderStatus_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t ExecTypeOrOrderStatus_internal_data_[];
inline constexpr ExecTypeOrOrderStatus ExecTypeOrOrderStatus_MIN =
    static_cast<ExecTypeOrOrderStatus>(0);
inline constexpr ExecTypeOrOrderStatus ExecTypeOrOrderStatus_MAX =
    static_cast<ExecTypeOrOrderStatus>(6);
inline bool ExecTypeOrOrderStatus_IsValid(int value) {
  return 0 <= value && value <= 6;
}
inline constexpr int ExecTypeOrOrderStatus_ARRAYSIZE = 6 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ExecTypeOrOrderStatus_descriptor();
template <typename T>
::absl::string_view ExecTypeOrOrderStatus_Name(T value) {
  static_assert(::std::is_same<T, ExecTypeOrOrderStatus>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ExecTypeOrOrderStatus_Name().");
  return ExecTypeOrOrderStatus_Name(static_cast<ExecTypeOrOrderStatus>(value));
}
template <>
inline ::absl::string_view ExecTypeOrOrderStatus_Name(ExecTypeOrOrderStatus value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ExecTypeOrOrderStatus_descriptor, 0, 6>(
      static_cast<int>(value));
}
inline bool ExecTypeOrOrderStatus_Parse(
    ::absl::string_view name, ExecTypeOrOrderStatus* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<ExecTypeOrOrderStatus>(ExecTypeOrOrderStatus_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class NewOrderSingleContainer final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:transport.NewOrderSingleContainer) */ {
 public:
  inline NewOrderSingleContainer() : NewOrderSingleContainer(nullptr) {}
  ~NewOrderSingleContainer() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(NewOrderSingleContainer* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(NewOrderSingleContainer));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NewOrderSingleContainer(::google::protobuf::internal::ConstantInitialized);

  inline NewOrderSingleContainer(const NewOrderSingleContainer& from) : NewOrderSingleContainer(nullptr, from) {}
  inline NewOrderSingleContainer(NewOrderSingleContainer&& from) noexcept
      : NewOrderSingleContainer(nullptr, ::std::move(from)) {}
  inline NewOrderSingleContainer& operator=(const NewOrderSingleContainer& from) {
    CopyFrom(from);
    return *this;
  }
  inline NewOrderSingleContainer& operator=(NewOrderSingleContainer&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NewOrderSingleContainer& default_instance() {
    return *reinterpret_cast<const NewOrderSingleContainer*>(
        &_NewOrderSingleContainer_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(NewOrderSingleContainer& a, NewOrderSingleContainer& b) { a.Swap(&b); }
  inline void Swap(NewOrderSingleContainer* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NewOrderSingleContainer* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NewOrderSingleContainer* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<NewOrderSingleContainer>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NewOrderSingleContainer& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NewOrderSingleContainer& from) { NewOrderSingleContainer::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(NewOrderSingleContainer* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "transport.NewOrderSingleContainer"; }

  explicit NewOrderSingleContainer(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  NewOrderSingleContainer(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const NewOrderSingleContainer& from);
  NewOrderSingleContainer(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, NewOrderSingleContainer&& from) noexcept
      : NewOrderSingleContainer(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSenderCompIdFieldNumber = 1,
    kTargetCompIdFieldNumber = 2,
    kClOrdIdFieldNumber = 3,
    kSymbolFieldNumber = 4,
    kOrderQtyFieldNumber = 6,
    kSideFieldNumber = 5,
    kOrdTypeFieldNumber = 7,
    kPriceFieldNumber = 8,
    kTimeInForceFieldNumber = 9,
  };
  // string sender_comp_id = 1;
  bool has_sender_comp_id() const;
  void clear_sender_comp_id() ;
  ::absl::string_view sender_comp_id() const;
  template <typename Arg_ = ::std::string&&>
  void set_sender_comp_id(Arg_&& arg);

  private:
  ::absl::string_view _internal_sender_comp_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_sender_comp_id(::absl::string_view value);

  public:
  // string target_comp_id = 2;
  bool has_target_comp_id() const;
  void clear_target_comp_id() ;
  ::absl::string_view target_comp_id() const;
  template <typename Arg_ = ::std::string&&>
  void set_target_comp_id(Arg_&& arg);

  private:
  ::absl::string_view _internal_target_comp_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_target_comp_id(::absl::string_view value);

  public:
  // string cl_ord_id = 3;
  bool has_cl_ord_id() const;
  void clear_cl_ord_id() ;
  ::absl::string_view cl_ord_id() const;
  template <typename Arg_ = ::std::string&&>
  void set_cl_ord_id(Arg_&& arg);

  private:
  ::absl::string_view _internal_cl_ord_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_cl_ord_id(::absl::string_view value);

  public:
  // string symbol = 4;
  bool has_symbol() const;
  void clear_symbol() ;
  ::absl::string_view symbol() const;
  template <typename Arg_ = ::std::string&&>
  void set_symbol(Arg_&& arg);

  private:
  ::absl::string_view _internal_symbol() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_symbol(::absl::string_view value);

  public:
  // double order_qty = 6;
  bool has_order_qty() const;
  void clear_order_qty() ;
  double order_qty() const;
  void set_order_qty(double value);

  private:
  double _internal_order_qty() const;
  void _internal_set_order_qty(double value);

  public:
  // .transport.Side side = 5;
  bool has_side() const;
  void clear_side() ;
  ::transport::Side side() const;
  void set_side(::transport::Side value);

  private:
  ::transport::Side _internal_side() const;
  void _internal_set_side(::transport::Side value);

  public:
  // .transport.OrderType ord_type = 7;
  bool has_ord_type() const;
  void clear_ord_type() ;
  ::transport::OrderType ord_type() const;
  void set_ord_type(::transport::OrderType value);

  private:
  ::transport::OrderType _internal_ord_type() const;
  void _internal_set_ord_type(::transport::OrderType value);

  public:
  // double price = 8;
  bool has_price() const;
  void clear_price() ;
  double price() const;
  void set_price(double value);

  private:
  double _internal_price() const;
  void _internal_set_price(double value);

  public:
  // .transport.TimeInForce time_in_force = 9;
  bool has_time_in_force() const;
  void clear_time_in_force() ;
  ::transport::TimeInForce time_in_force() const;
  void set_time_in_force(::transport::TimeInForce value);

  private:
  ::transport::TimeInForce _internal_time_in_force() const;
  void _internal_set_time_in_force(::transport::TimeInForce value);

  public:
  // @@protoc_insertion_point(class_scope:transport.NewOrderSingleContainer)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 9,
                                   0, 93,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const NewOrderSingleContainer& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr sender_comp_id_;
    ::google::protobuf::internal::ArenaStringPtr target_comp_id_;
    ::google::protobuf::internal::ArenaStringPtr cl_ord_id_;
    ::google::protobuf::internal::ArenaStringPtr symbol_;
    double order_qty_;
    int side_;
    int ord_type_;
    double price_;
    int time_in_force_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_containers_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull NewOrderSingleContainer_class_data_;
// -------------------------------------------------------------------

class ExecutionReportContainer final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:transport.ExecutionReportContainer) */ {
 public:
  inline ExecutionReportContainer() : ExecutionReportContainer(nullptr) {}
  ~ExecutionReportContainer() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ExecutionReportContainer* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ExecutionReportContainer));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ExecutionReportContainer(::google::protobuf::internal::ConstantInitialized);

  inline ExecutionReportContainer(const ExecutionReportContainer& from) : ExecutionReportContainer(nullptr, from) {}
  inline ExecutionReportContainer(ExecutionReportContainer&& from) noexcept
      : ExecutionReportContainer(nullptr, ::std::move(from)) {}
  inline ExecutionReportContainer& operator=(const ExecutionReportContainer& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExecutionReportContainer& operator=(ExecutionReportContainer&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ExecutionReportContainer& default_instance() {
    return *reinterpret_cast<const ExecutionReportContainer*>(
        &_ExecutionReportContainer_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ExecutionReportContainer& a, ExecutionReportContainer& b) { a.Swap(&b); }
  inline void Swap(ExecutionReportContainer* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExecutionReportContainer* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ExecutionReportContainer* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ExecutionReportContainer>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ExecutionReportContainer& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ExecutionReportContainer& from) { ExecutionReportContainer::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ExecutionReportContainer* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "transport.ExecutionReportContainer"; }

  explicit ExecutionReportContainer(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ExecutionReportContainer(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ExecutionReportContainer& from);
  ExecutionReportContainer(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ExecutionReportContainer&& from) noexcept
      : ExecutionReportContainer(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSenderCompIdFieldNumber = 1,
    kTargetCompIdFieldNumber = 2,
    kOrderIdFieldNumber = 3,
    kClOrderIdFieldNumber = 4,
    kOrigClOrdIdFieldNumber = 5,
    kExecIdFieldNumber = 6,
    kOrdRejectReasonFieldNumber = 10,
    kSymbolFieldNumber = 11,
    kExecTransTypeFieldNumber = 7,
    kExecTypeFieldNumber = 8,
    kOrdStatusFieldNumber = 9,
    kSideFieldNumber = 12,
    kPriceFieldNumber = 13,
    kLeavesQtyFieldNumber = 15,
    kCumQtyFieldNumber = 16,
    kAvgPxFieldNumber = 17,
    kTimeInForceFieldNumber = 14,
  };
  // string sender_comp_id = 1;
  bool has_sender_comp_id() const;
  void clear_sender_comp_id() ;
  ::absl::string_view sender_comp_id() const;
  template <typename Arg_ = ::std::string&&>
  void set_sender_comp_id(Arg_&& arg);

  private:
  ::absl::string_view _internal_sender_comp_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_sender_comp_id(::absl::string_view value);

  public:
  // string target_comp_id = 2;
  bool has_target_comp_id() const;
  void clear_target_comp_id() ;
  ::absl::string_view target_comp_id() const;
  template <typename Arg_ = ::std::string&&>
  void set_target_comp_id(Arg_&& arg);

  private:
  ::absl::string_view _internal_target_comp_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_target_comp_id(::absl::string_view value);

  public:
  // string order_id = 3;
  bool has_order_id() const;
  void clear_order_id() ;
  ::absl::string_view order_id() const;
  template <typename Arg_ = ::std::string&&>
  void set_order_id(Arg_&& arg);

  private:
  ::absl::string_view _internal_order_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_order_id(::absl::string_view value);

  public:
  // string cl_order_id = 4;
  bool has_cl_order_id() const;
  void clear_cl_order_id() ;
  ::absl::string_view cl_order_id() const;
  template <typename Arg_ = ::std::string&&>
  void set_cl_order_id(Arg_&& arg);

  private:
  ::absl::string_view _internal_cl_order_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_cl_order_id(::absl::string_view value);

  public:
  // string orig_cl_ord_id = 5;
  bool has_orig_cl_ord_id() const;
  void clear_orig_cl_ord_id() ;
  ::absl::string_view orig_cl_ord_id() const;
  template <typename Arg_ = ::std::string&&>
  void set_orig_cl_ord_id(Arg_&& arg);

  private:
  ::absl::string_view _internal_orig_cl_ord_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_orig_cl_ord_id(::absl::string_view value);

  public:
  // string exec_id = 6;
  bool has_exec_id() const;
  void clear_exec_id() ;
  ::absl::string_view exec_id() const;
  template <typename Arg_ = ::std::string&&>
  void set_exec_id(Arg_&& arg);

  private:
  ::absl::string_view _internal_exec_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_exec_id(::absl::string_view value);

  public:
  // string ord_reject_reason = 10;
  bool has_ord_reject_reason() const;
  void clear_ord_reject_reason() ;
  ::absl::string_view ord_reject_reason() const;
  template <typename Arg_ = ::std::string&&>
  void set_ord_reject_reason(Arg_&& arg);

  private:
  ::absl::string_view _internal_ord_reject_reason() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_ord_reject_reason(::absl::string_view value);

  public:
  // string symbol = 11;
  bool has_symbol() const;
  void clear_symbol() ;
  ::absl::string_view symbol() const;
  template <typename Arg_ = ::std::string&&>
  void set_symbol(Arg_&& arg);

  private:
  ::absl::string_view _internal_symbol() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_symbol(::absl::string_view value);

  public:
  // .transport.ExecTransType exec_trans_type = 7;
  bool has_exec_trans_type() const;
  void clear_exec_trans_type() ;
  ::transport::ExecTransType exec_trans_type() const;
  void set_exec_trans_type(::transport::ExecTransType value);

  private:
  ::transport::ExecTransType _internal_exec_trans_type() const;
  void _internal_set_exec_trans_type(::transport::ExecTransType value);

  public:
  // .transport.ExecTypeOrOrderStatus exec_type = 8;
  bool has_exec_type() const;
  void clear_exec_type() ;
  ::transport::ExecTypeOrOrderStatus exec_type() const;
  void set_exec_type(::transport::ExecTypeOrOrderStatus value);

  private:
  ::transport::ExecTypeOrOrderStatus _internal_exec_type() const;
  void _internal_set_exec_type(::transport::ExecTypeOrOrderStatus value);

  public:
  // .transport.ExecTypeOrOrderStatus ord_status = 9;
  bool has_ord_status() const;
  void clear_ord_status() ;
  ::transport::ExecTypeOrOrderStatus ord_status() const;
  void set_ord_status(::transport::ExecTypeOrOrderStatus value);

  private:
  ::transport::ExecTypeOrOrderStatus _internal_ord_status() const;
  void _internal_set_ord_status(::transport::ExecTypeOrOrderStatus value);

  public:
  // .transport.Side side = 12;
  bool has_side() const;
  void clear_side() ;
  ::transport::Side side() const;
  void set_side(::transport::Side value);

  private:
  ::transport::Side _internal_side() const;
  void _internal_set_side(::transport::Side value);

  public:
  // double price = 13;
  bool has_price() const;
  void clear_price() ;
  double price() const;
  void set_price(double value);

  private:
  double _internal_price() const;
  void _internal_set_price(double value);

  public:
  // double leaves_qty = 15;
  bool has_leaves_qty() const;
  void clear_leaves_qty() ;
  double leaves_qty() const;
  void set_leaves_qty(double value);

  private:
  double _internal_leaves_qty() const;
  void _internal_set_leaves_qty(double value);

  public:
  // double cum_qty = 16;
  bool has_cum_qty() const;
  void clear_cum_qty() ;
  double cum_qty() const;
  void set_cum_qty(double value);

  private:
  double _internal_cum_qty() const;
  void _internal_set_cum_qty(double value);

  public:
  // double avg_px = 17;
  bool has_avg_px() const;
  void clear_avg_px() ;
  double avg_px() const;
  void set_avg_px(double value);

  private:
  double _internal_avg_px() const;
  void _internal_set_avg_px(double value);

  public:
  // .transport.TimeInForce time_in_force = 14;
  bool has_time_in_force() const;
  void clear_time_in_force() ;
  ::transport::TimeInForce time_in_force() const;
  void set_time_in_force(::transport::TimeInForce value);

  private:
  ::transport::TimeInForce _internal_time_in_force() const;
  void _internal_set_time_in_force(::transport::TimeInForce value);

  public:
  // @@protoc_insertion_point(class_scope:transport.ExecutionReportContainer)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<5, 17,
                                   0, 150,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ExecutionReportContainer& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr sender_comp_id_;
    ::google::protobuf::internal::ArenaStringPtr target_comp_id_;
    ::google::protobuf::internal::ArenaStringPtr order_id_;
    ::google::protobuf::internal::ArenaStringPtr cl_order_id_;
    ::google::protobuf::internal::ArenaStringPtr orig_cl_ord_id_;
    ::google::protobuf::internal::ArenaStringPtr exec_id_;
    ::google::protobuf::internal::ArenaStringPtr ord_reject_reason_;
    ::google::protobuf::internal::ArenaStringPtr symbol_;
    int exec_trans_type_;
    int exec_type_;
    int ord_status_;
    int side_;
    double price_;
    double leaves_qty_;
    double cum_qty_;
    double avg_px_;
    int time_in_force_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_containers_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ExecutionReportContainer_class_data_;
// -------------------------------------------------------------------

class CancelOrderRequestContainer final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:transport.CancelOrderRequestContainer) */ {
 public:
  inline CancelOrderRequestContainer() : CancelOrderRequestContainer(nullptr) {}
  ~CancelOrderRequestContainer() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CancelOrderRequestContainer* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CancelOrderRequestContainer));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CancelOrderRequestContainer(::google::protobuf::internal::ConstantInitialized);

  inline CancelOrderRequestContainer(const CancelOrderRequestContainer& from) : CancelOrderRequestContainer(nullptr, from) {}
  inline CancelOrderRequestContainer(CancelOrderRequestContainer&& from) noexcept
      : CancelOrderRequestContainer(nullptr, ::std::move(from)) {}
  inline CancelOrderRequestContainer& operator=(const CancelOrderRequestContainer& from) {
    CopyFrom(from);
    return *this;
  }
  inline CancelOrderRequestContainer& operator=(CancelOrderRequestContainer&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CancelOrderRequestContainer& default_instance() {
    return *reinterpret_cast<const CancelOrderRequestContainer*>(
        &_CancelOrderRequestContainer_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CancelOrderRequestContainer& a, CancelOrderRequestContainer& b) { a.Swap(&b); }
  inline void Swap(CancelOrderRequestContainer* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CancelOrderRequestContainer* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CancelOrderRequestContainer* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CancelOrderRequestContainer>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CancelOrderRequestContainer& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CancelOrderRequestContainer& from) { CancelOrderRequestContainer::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CancelOrderRequestContainer* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "transport.CancelOrderRequestContainer"; }

  explicit CancelOrderRequestContainer(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CancelOrderRequestContainer(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CancelOrderRequestContainer& from);
  CancelOrderRequestContainer(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CancelOrderRequestContainer&& from) noexcept
      : CancelOrderRequestContainer(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSenderCompIdFieldNumber = 1,
    kTargetCompIdFieldNumber = 2,
    kOrderIdFieldNumber = 3,
    kOrigClOrdIdFieldNumber = 4,
    kClOrdIdFieldNumber = 5,
    kSymbolFieldNumber = 6,
    kOrderQtyFieldNumber = 8,
    kSideFieldNumber = 7,
  };
  // string sender_comp_id = 1;
  bool has_sender_comp_id() const;
  void clear_sender_comp_id() ;
  ::absl::string_view sender_comp_id() const;
  template <typename Arg_ = ::std::string&&>
  void set_sender_comp_id(Arg_&& arg);

  private:
  ::absl::string_view _internal_sender_comp_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_sender_comp_id(::absl::string_view value);

  public:
  // string target_comp_id = 2;
  bool has_target_comp_id() const;
  void clear_target_comp_id() ;
  ::absl::string_view target_comp_id() const;
  template <typename Arg_ = ::std::string&&>
  void set_target_comp_id(Arg_&& arg);

  private:
  ::absl::string_view _internal_target_comp_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_target_comp_id(::absl::string_view value);

  public:
  // string order_id = 3;
  bool has_order_id() const;
  void clear_order_id() ;
  ::absl::string_view order_id() const;
  template <typename Arg_ = ::std::string&&>
  void set_order_id(Arg_&& arg);

  private:
  ::absl::string_view _internal_order_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_order_id(::absl::string_view value);

  public:
  // string orig_cl_ord_id = 4;
  bool has_orig_cl_ord_id() const;
  void clear_orig_cl_ord_id() ;
  ::absl::string_view orig_cl_ord_id() const;
  template <typename Arg_ = ::std::string&&>
  void set_orig_cl_ord_id(Arg_&& arg);

  private:
  ::absl::string_view _internal_orig_cl_ord_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_orig_cl_ord_id(::absl::string_view value);

  public:
  // string cl_ord_id = 5;
  bool has_cl_ord_id() const;
  void clear_cl_ord_id() ;
  ::absl::string_view cl_ord_id() const;
  template <typename Arg_ = ::std::string&&>
  void set_cl_ord_id(Arg_&& arg);

  private:
  ::absl::string_view _internal_cl_ord_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_cl_ord_id(::absl::string_view value);

  public:
  // string symbol = 6;
  bool has_symbol() const;
  void clear_symbol() ;
  ::absl::string_view symbol() const;
  template <typename Arg_ = ::std::string&&>
  void set_symbol(Arg_&& arg);

  private:
  ::absl::string_view _internal_symbol() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_symbol(::absl::string_view value);

  public:
  // double order_qty = 8;
  bool has_order_qty() const;
  void clear_order_qty() ;
  double order_qty() const;
  void set_order_qty(double value);

  private:
  double _internal_order_qty() const;
  void _internal_set_order_qty(double value);

  public:
  // .transport.Side side = 7;
  bool has_side() const;
  void clear_side() ;
  ::transport::Side side() const;
  void set_side(::transport::Side value);

  private:
  ::transport::Side _internal_side() const;
  void _internal_set_side(::transport::Side value);

  public:
  // @@protoc_insertion_point(class_scope:transport.CancelOrderRequestContainer)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8,
                                   0, 119,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CancelOrderRequestContainer& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr sender_comp_id_;
    ::google::protobuf::internal::ArenaStringPtr target_comp_id_;
    ::google::protobuf::internal::ArenaStringPtr order_id_;
    ::google::protobuf::internal::ArenaStringPtr orig_cl_ord_id_;
    ::google::protobuf::internal::ArenaStringPtr cl_ord_id_;
    ::google::protobuf::internal::ArenaStringPtr symbol_;
    double order_qty_;
    int side_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_containers_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CancelOrderRequestContainer_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// NewOrderSingleContainer

// string sender_comp_id = 1;
inline bool NewOrderSingleContainer::has_sender_comp_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void NewOrderSingleContainer::clear_sender_comp_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sender_comp_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::absl::string_view NewOrderSingleContainer::sender_comp_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transport.NewOrderSingleContainer.sender_comp_id)
  return _internal_sender_comp_id();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void NewOrderSingleContainer::set_sender_comp_id(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.sender_comp_id_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:transport.NewOrderSingleContainer.sender_comp_id)
}
inline ::absl::string_view NewOrderSingleContainer::_internal_sender_comp_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sender_comp_id_.Get();
}
inline void NewOrderSingleContainer::_internal_set_sender_comp_id(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.sender_comp_id_.Set(value, GetArena());
}

// string target_comp_id = 2;
inline bool NewOrderSingleContainer::has_target_comp_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void NewOrderSingleContainer::clear_target_comp_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_comp_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::absl::string_view NewOrderSingleContainer::target_comp_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transport.NewOrderSingleContainer.target_comp_id)
  return _internal_target_comp_id();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void NewOrderSingleContainer::set_target_comp_id(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.target_comp_id_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:transport.NewOrderSingleContainer.target_comp_id)
}
inline ::absl::string_view NewOrderSingleContainer::_internal_target_comp_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.target_comp_id_.Get();
}
inline void NewOrderSingleContainer::_internal_set_target_comp_id(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.target_comp_id_.Set(value, GetArena());
}

// string cl_ord_id = 3;
inline bool NewOrderSingleContainer::has_cl_ord_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void NewOrderSingleContainer::clear_cl_ord_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cl_ord_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::absl::string_view NewOrderSingleContainer::cl_ord_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transport.NewOrderSingleContainer.cl_ord_id)
  return _internal_cl_ord_id();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void NewOrderSingleContainer::set_cl_ord_id(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.cl_ord_id_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:transport.NewOrderSingleContainer.cl_ord_id)
}
inline ::absl::string_view NewOrderSingleContainer::_internal_cl_ord_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cl_ord_id_.Get();
}
inline void NewOrderSingleContainer::_internal_set_cl_ord_id(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.cl_ord_id_.Set(value, GetArena());
}

// string symbol = 4;
inline bool NewOrderSingleContainer::has_symbol() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void NewOrderSingleContainer::clear_symbol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.symbol_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::absl::string_view NewOrderSingleContainer::symbol() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transport.NewOrderSingleContainer.symbol)
  return _internal_symbol();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void NewOrderSingleContainer::set_symbol(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.symbol_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:transport.NewOrderSingleContainer.symbol)
}
inline ::absl::string_view NewOrderSingleContainer::_internal_symbol() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.symbol_.Get();
}
inline void NewOrderSingleContainer::_internal_set_symbol(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.symbol_.Set(value, GetArena());
}

// .transport.Side side = 5;
inline bool NewOrderSingleContainer::has_side() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void NewOrderSingleContainer::clear_side() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.side_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::transport::Side NewOrderSingleContainer::side() const {
  // @@protoc_insertion_point(field_get:transport.NewOrderSingleContainer.side)
  return _internal_side();
}
inline void NewOrderSingleContainer::set_side(::transport::Side value) {
  _internal_set_side(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:transport.NewOrderSingleContainer.side)
}
inline ::transport::Side NewOrderSingleContainer::_internal_side() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::transport::Side>(_impl_.side_);
}
inline void NewOrderSingleContainer::_internal_set_side(::transport::Side value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.side_ = value;
}

// double order_qty = 6;
inline bool NewOrderSingleContainer::has_order_qty() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void NewOrderSingleContainer::clear_order_qty() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.order_qty_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline double NewOrderSingleContainer::order_qty() const {
  // @@protoc_insertion_point(field_get:transport.NewOrderSingleContainer.order_qty)
  return _internal_order_qty();
}
inline void NewOrderSingleContainer::set_order_qty(double value) {
  _internal_set_order_qty(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:transport.NewOrderSingleContainer.order_qty)
}
inline double NewOrderSingleContainer::_internal_order_qty() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.order_qty_;
}
inline void NewOrderSingleContainer::_internal_set_order_qty(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.order_qty_ = value;
}

// .transport.OrderType ord_type = 7;
inline bool NewOrderSingleContainer::has_ord_type() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000040U);
  return value;
}
inline void NewOrderSingleContainer::clear_ord_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ord_type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::transport::OrderType NewOrderSingleContainer::ord_type() const {
  // @@protoc_insertion_point(field_get:transport.NewOrderSingleContainer.ord_type)
  return _internal_ord_type();
}
inline void NewOrderSingleContainer::set_ord_type(::transport::OrderType value) {
  _internal_set_ord_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:transport.NewOrderSingleContainer.ord_type)
}
inline ::transport::OrderType NewOrderSingleContainer::_internal_ord_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::transport::OrderType>(_impl_.ord_type_);
}
inline void NewOrderSingleContainer::_internal_set_ord_type(::transport::OrderType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ord_type_ = value;
}

// double price = 8;
inline bool NewOrderSingleContainer::has_price() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000080U);
  return value;
}
inline void NewOrderSingleContainer::clear_price() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.price_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline double NewOrderSingleContainer::price() const {
  // @@protoc_insertion_point(field_get:transport.NewOrderSingleContainer.price)
  return _internal_price();
}
inline void NewOrderSingleContainer::set_price(double value) {
  _internal_set_price(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:transport.NewOrderSingleContainer.price)
}
inline double NewOrderSingleContainer::_internal_price() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.price_;
}
inline void NewOrderSingleContainer::_internal_set_price(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.price_ = value;
}

// .transport.TimeInForce time_in_force = 9;
inline bool NewOrderSingleContainer::has_time_in_force() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000100U);
  return value;
}
inline void NewOrderSingleContainer::clear_time_in_force() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_in_force_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline ::transport::TimeInForce NewOrderSingleContainer::time_in_force() const {
  // @@protoc_insertion_point(field_get:transport.NewOrderSingleContainer.time_in_force)
  return _internal_time_in_force();
}
inline void NewOrderSingleContainer::set_time_in_force(::transport::TimeInForce value) {
  _internal_set_time_in_force(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:transport.NewOrderSingleContainer.time_in_force)
}
inline ::transport::TimeInForce NewOrderSingleContainer::_internal_time_in_force() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::transport::TimeInForce>(_impl_.time_in_force_);
}
inline void NewOrderSingleContainer::_internal_set_time_in_force(::transport::TimeInForce value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_in_force_ = value;
}

// -------------------------------------------------------------------

// CancelOrderRequestContainer

// string sender_comp_id = 1;
inline bool CancelOrderRequestContainer::has_sender_comp_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CancelOrderRequestContainer::clear_sender_comp_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sender_comp_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::absl::string_view CancelOrderRequestContainer::sender_comp_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transport.CancelOrderRequestContainer.sender_comp_id)
  return _internal_sender_comp_id();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void CancelOrderRequestContainer::set_sender_comp_id(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.sender_comp_id_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:transport.CancelOrderRequestContainer.sender_comp_id)
}
inline ::absl::string_view CancelOrderRequestContainer::_internal_sender_comp_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sender_comp_id_.Get();
}
inline void CancelOrderRequestContainer::_internal_set_sender_comp_id(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.sender_comp_id_.Set(value, GetArena());
}

// string target_comp_id = 2;
inline bool CancelOrderRequestContainer::has_target_comp_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void CancelOrderRequestContainer::clear_target_comp_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_comp_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::absl::string_view CancelOrderRequestContainer::target_comp_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transport.CancelOrderRequestContainer.target_comp_id)
  return _internal_target_comp_id();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void CancelOrderRequestContainer::set_target_comp_id(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.target_comp_id_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:transport.CancelOrderRequestContainer.target_comp_id)
}
inline ::absl::string_view CancelOrderRequestContainer::_internal_target_comp_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.target_comp_id_.Get();
}
inline void CancelOrderRequestContainer::_internal_set_target_comp_id(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.target_comp_id_.Set(value, GetArena());
}

// string order_id = 3;
inline bool CancelOrderRequestContainer::has_order_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void CancelOrderRequestContainer::clear_order_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.order_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::absl::string_view CancelOrderRequestContainer::order_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transport.CancelOrderRequestContainer.order_id)
  return _internal_order_id();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void CancelOrderRequestContainer::set_order_id(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.order_id_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:transport.CancelOrderRequestContainer.order_id)
}
inline ::absl::string_view CancelOrderRequestContainer::_internal_order_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.order_id_.Get();
}
inline void CancelOrderRequestContainer::_internal_set_order_id(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.order_id_.Set(value, GetArena());
}

// string orig_cl_ord_id = 4;
inline bool CancelOrderRequestContainer::has_orig_cl_ord_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void CancelOrderRequestContainer::clear_orig_cl_ord_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.orig_cl_ord_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::absl::string_view CancelOrderRequestContainer::orig_cl_ord_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transport.CancelOrderRequestContainer.orig_cl_ord_id)
  return _internal_orig_cl_ord_id();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void CancelOrderRequestContainer::set_orig_cl_ord_id(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.orig_cl_ord_id_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:transport.CancelOrderRequestContainer.orig_cl_ord_id)
}
inline ::absl::string_view CancelOrderRequestContainer::_internal_orig_cl_ord_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.orig_cl_ord_id_.Get();
}
inline void CancelOrderRequestContainer::_internal_set_orig_cl_ord_id(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.orig_cl_ord_id_.Set(value, GetArena());
}

// string cl_ord_id = 5;
inline bool CancelOrderRequestContainer::has_cl_ord_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void CancelOrderRequestContainer::clear_cl_ord_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cl_ord_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::absl::string_view CancelOrderRequestContainer::cl_ord_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transport.CancelOrderRequestContainer.cl_ord_id)
  return _internal_cl_ord_id();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void CancelOrderRequestContainer::set_cl_ord_id(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.cl_ord_id_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:transport.CancelOrderRequestContainer.cl_ord_id)
}
inline ::absl::string_view CancelOrderRequestContainer::_internal_cl_ord_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cl_ord_id_.Get();
}
inline void CancelOrderRequestContainer::_internal_set_cl_ord_id(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.cl_ord_id_.Set(value, GetArena());
}

// string symbol = 6;
inline bool CancelOrderRequestContainer::has_symbol() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void CancelOrderRequestContainer::clear_symbol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.symbol_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::absl::string_view CancelOrderRequestContainer::symbol() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transport.CancelOrderRequestContainer.symbol)
  return _internal_symbol();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void CancelOrderRequestContainer::set_symbol(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  _impl_.symbol_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:transport.CancelOrderRequestContainer.symbol)
}
inline ::absl::string_view CancelOrderRequestContainer::_internal_symbol() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.symbol_.Get();
}
inline void CancelOrderRequestContainer::_internal_set_symbol(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  _impl_.symbol_.Set(value, GetArena());
}

// .transport.Side side = 7;
inline bool CancelOrderRequestContainer::has_side() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000080U);
  return value;
}
inline void CancelOrderRequestContainer::clear_side() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.side_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::transport::Side CancelOrderRequestContainer::side() const {
  // @@protoc_insertion_point(field_get:transport.CancelOrderRequestContainer.side)
  return _internal_side();
}
inline void CancelOrderRequestContainer::set_side(::transport::Side value) {
  _internal_set_side(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:transport.CancelOrderRequestContainer.side)
}
inline ::transport::Side CancelOrderRequestContainer::_internal_side() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::transport::Side>(_impl_.side_);
}
inline void CancelOrderRequestContainer::_internal_set_side(::transport::Side value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.side_ = value;
}

// double order_qty = 8;
inline bool CancelOrderRequestContainer::has_order_qty() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000040U);
  return value;
}
inline void CancelOrderRequestContainer::clear_order_qty() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.order_qty_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline double CancelOrderRequestContainer::order_qty() const {
  // @@protoc_insertion_point(field_get:transport.CancelOrderRequestContainer.order_qty)
  return _internal_order_qty();
}
inline void CancelOrderRequestContainer::set_order_qty(double value) {
  _internal_set_order_qty(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:transport.CancelOrderRequestContainer.order_qty)
}
inline double CancelOrderRequestContainer::_internal_order_qty() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.order_qty_;
}
inline void CancelOrderRequestContainer::_internal_set_order_qty(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.order_qty_ = value;
}

// -------------------------------------------------------------------

// ExecutionReportContainer

// string sender_comp_id = 1;
inline bool ExecutionReportContainer::has_sender_comp_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void ExecutionReportContainer::clear_sender_comp_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sender_comp_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::absl::string_view ExecutionReportContainer::sender_comp_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transport.ExecutionReportContainer.sender_comp_id)
  return _internal_sender_comp_id();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void ExecutionReportContainer::set_sender_comp_id(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.sender_comp_id_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:transport.ExecutionReportContainer.sender_comp_id)
}
inline ::absl::string_view ExecutionReportContainer::_internal_sender_comp_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sender_comp_id_.Get();
}
inline void ExecutionReportContainer::_internal_set_sender_comp_id(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.sender_comp_id_.Set(value, GetArena());
}

// string target_comp_id = 2;
inline bool ExecutionReportContainer::has_target_comp_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void ExecutionReportContainer::clear_target_comp_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_comp_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::absl::string_view ExecutionReportContainer::target_comp_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transport.ExecutionReportContainer.target_comp_id)
  return _internal_target_comp_id();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void ExecutionReportContainer::set_target_comp_id(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.target_comp_id_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:transport.ExecutionReportContainer.target_comp_id)
}
inline ::absl::string_view ExecutionReportContainer::_internal_target_comp_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.target_comp_id_.Get();
}
inline void ExecutionReportContainer::_internal_set_target_comp_id(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.target_comp_id_.Set(value, GetArena());
}

// string order_id = 3;
inline bool ExecutionReportContainer::has_order_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void ExecutionReportContainer::clear_order_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.order_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::absl::string_view ExecutionReportContainer::order_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transport.ExecutionReportContainer.order_id)
  return _internal_order_id();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void ExecutionReportContainer::set_order_id(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.order_id_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:transport.ExecutionReportContainer.order_id)
}
inline ::absl::string_view ExecutionReportContainer::_internal_order_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.order_id_.Get();
}
inline void ExecutionReportContainer::_internal_set_order_id(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.order_id_.Set(value, GetArena());
}

// string cl_order_id = 4;
inline bool ExecutionReportContainer::has_cl_order_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void ExecutionReportContainer::clear_cl_order_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cl_order_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::absl::string_view ExecutionReportContainer::cl_order_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transport.ExecutionReportContainer.cl_order_id)
  return _internal_cl_order_id();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void ExecutionReportContainer::set_cl_order_id(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.cl_order_id_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:transport.ExecutionReportContainer.cl_order_id)
}
inline ::absl::string_view ExecutionReportContainer::_internal_cl_order_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cl_order_id_.Get();
}
inline void ExecutionReportContainer::_internal_set_cl_order_id(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.cl_order_id_.Set(value, GetArena());
}

// string orig_cl_ord_id = 5;
inline bool ExecutionReportContainer::has_orig_cl_ord_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void ExecutionReportContainer::clear_orig_cl_ord_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.orig_cl_ord_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::absl::string_view ExecutionReportContainer::orig_cl_ord_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transport.ExecutionReportContainer.orig_cl_ord_id)
  return _internal_orig_cl_ord_id();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void ExecutionReportContainer::set_orig_cl_ord_id(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.orig_cl_ord_id_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:transport.ExecutionReportContainer.orig_cl_ord_id)
}
inline ::absl::string_view ExecutionReportContainer::_internal_orig_cl_ord_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.orig_cl_ord_id_.Get();
}
inline void ExecutionReportContainer::_internal_set_orig_cl_ord_id(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.orig_cl_ord_id_.Set(value, GetArena());
}

// string exec_id = 6;
inline bool ExecutionReportContainer::has_exec_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void ExecutionReportContainer::clear_exec_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exec_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::absl::string_view ExecutionReportContainer::exec_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transport.ExecutionReportContainer.exec_id)
  return _internal_exec_id();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void ExecutionReportContainer::set_exec_id(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  _impl_.exec_id_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:transport.ExecutionReportContainer.exec_id)
}
inline ::absl::string_view ExecutionReportContainer::_internal_exec_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.exec_id_.Get();
}
inline void ExecutionReportContainer::_internal_set_exec_id(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  _impl_.exec_id_.Set(value, GetArena());
}

// .transport.ExecTransType exec_trans_type = 7;
inline bool ExecutionReportContainer::has_exec_trans_type() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000100U);
  return value;
}
inline void ExecutionReportContainer::clear_exec_trans_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exec_trans_type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline ::transport::ExecTransType ExecutionReportContainer::exec_trans_type() const {
  // @@protoc_insertion_point(field_get:transport.ExecutionReportContainer.exec_trans_type)
  return _internal_exec_trans_type();
}
inline void ExecutionReportContainer::set_exec_trans_type(::transport::ExecTransType value) {
  _internal_set_exec_trans_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:transport.ExecutionReportContainer.exec_trans_type)
}
inline ::transport::ExecTransType ExecutionReportContainer::_internal_exec_trans_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::transport::ExecTransType>(_impl_.exec_trans_type_);
}
inline void ExecutionReportContainer::_internal_set_exec_trans_type(::transport::ExecTransType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exec_trans_type_ = value;
}

// .transport.ExecTypeOrOrderStatus exec_type = 8;
inline bool ExecutionReportContainer::has_exec_type() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000200U);
  return value;
}
inline void ExecutionReportContainer::clear_exec_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exec_type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000200U);
}
inline ::transport::ExecTypeOrOrderStatus ExecutionReportContainer::exec_type() const {
  // @@protoc_insertion_point(field_get:transport.ExecutionReportContainer.exec_type)
  return _internal_exec_type();
}
inline void ExecutionReportContainer::set_exec_type(::transport::ExecTypeOrOrderStatus value) {
  _internal_set_exec_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_set:transport.ExecutionReportContainer.exec_type)
}
inline ::transport::ExecTypeOrOrderStatus ExecutionReportContainer::_internal_exec_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::transport::ExecTypeOrOrderStatus>(_impl_.exec_type_);
}
inline void ExecutionReportContainer::_internal_set_exec_type(::transport::ExecTypeOrOrderStatus value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exec_type_ = value;
}

// .transport.ExecTypeOrOrderStatus ord_status = 9;
inline bool ExecutionReportContainer::has_ord_status() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000400U);
  return value;
}
inline void ExecutionReportContainer::clear_ord_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ord_status_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000400U);
}
inline ::transport::ExecTypeOrOrderStatus ExecutionReportContainer::ord_status() const {
  // @@protoc_insertion_point(field_get:transport.ExecutionReportContainer.ord_status)
  return _internal_ord_status();
}
inline void ExecutionReportContainer::set_ord_status(::transport::ExecTypeOrOrderStatus value) {
  _internal_set_ord_status(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000400U);
  // @@protoc_insertion_point(field_set:transport.ExecutionReportContainer.ord_status)
}
inline ::transport::ExecTypeOrOrderStatus ExecutionReportContainer::_internal_ord_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::transport::ExecTypeOrOrderStatus>(_impl_.ord_status_);
}
inline void ExecutionReportContainer::_internal_set_ord_status(::transport::ExecTypeOrOrderStatus value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ord_status_ = value;
}

// string ord_reject_reason = 10;
inline bool ExecutionReportContainer::has_ord_reject_reason() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000040U);
  return value;
}
inline void ExecutionReportContainer::clear_ord_reject_reason() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ord_reject_reason_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::absl::string_view ExecutionReportContainer::ord_reject_reason() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transport.ExecutionReportContainer.ord_reject_reason)
  return _internal_ord_reject_reason();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void ExecutionReportContainer::set_ord_reject_reason(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  _impl_.ord_reject_reason_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:transport.ExecutionReportContainer.ord_reject_reason)
}
inline ::absl::string_view ExecutionReportContainer::_internal_ord_reject_reason() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ord_reject_reason_.Get();
}
inline void ExecutionReportContainer::_internal_set_ord_reject_reason(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  _impl_.ord_reject_reason_.Set(value, GetArena());
}

// string symbol = 11;
inline bool ExecutionReportContainer::has_symbol() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000080U);
  return value;
}
inline void ExecutionReportContainer::clear_symbol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.symbol_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::absl::string_view ExecutionReportContainer::symbol() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transport.ExecutionReportContainer.symbol)
  return _internal_symbol();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void ExecutionReportContainer::set_symbol(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  _impl_.symbol_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:transport.ExecutionReportContainer.symbol)
}
inline ::absl::string_view ExecutionReportContainer::_internal_symbol() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.symbol_.Get();
}
inline void ExecutionReportContainer::_internal_set_symbol(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  _impl_.symbol_.Set(value, GetArena());
}

// .transport.Side side = 12;
inline bool ExecutionReportContainer::has_side() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000800U);
  return value;
}
inline void ExecutionReportContainer::clear_side() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.side_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000800U);
}
inline ::transport::Side ExecutionReportContainer::side() const {
  // @@protoc_insertion_point(field_get:transport.ExecutionReportContainer.side)
  return _internal_side();
}
inline void ExecutionReportContainer::set_side(::transport::Side value) {
  _internal_set_side(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000800U);
  // @@protoc_insertion_point(field_set:transport.ExecutionReportContainer.side)
}
inline ::transport::Side ExecutionReportContainer::_internal_side() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::transport::Side>(_impl_.side_);
}
inline void ExecutionReportContainer::_internal_set_side(::transport::Side value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.side_ = value;
}

// double price = 13;
inline bool ExecutionReportContainer::has_price() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00001000U);
  return value;
}
inline void ExecutionReportContainer::clear_price() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.price_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00001000U);
}
inline double ExecutionReportContainer::price() const {
  // @@protoc_insertion_point(field_get:transport.ExecutionReportContainer.price)
  return _internal_price();
}
inline void ExecutionReportContainer::set_price(double value) {
  _internal_set_price(value);
  SetHasBit(_impl_._has_bits_[0], 0x00001000U);
  // @@protoc_insertion_point(field_set:transport.ExecutionReportContainer.price)
}
inline double ExecutionReportContainer::_internal_price() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.price_;
}
inline void ExecutionReportContainer::_internal_set_price(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.price_ = value;
}

// .transport.TimeInForce time_in_force = 14;
inline bool ExecutionReportContainer::has_time_in_force() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00010000U);
  return value;
}
inline void ExecutionReportContainer::clear_time_in_force() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_in_force_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00010000U);
}
inline ::transport::TimeInForce ExecutionReportContainer::time_in_force() const {
  // @@protoc_insertion_point(field_get:transport.ExecutionReportContainer.time_in_force)
  return _internal_time_in_force();
}
inline void ExecutionReportContainer::set_time_in_force(::transport::TimeInForce value) {
  _internal_set_time_in_force(value);
  SetHasBit(_impl_._has_bits_[0], 0x00010000U);
  // @@protoc_insertion_point(field_set:transport.ExecutionReportContainer.time_in_force)
}
inline ::transport::TimeInForce ExecutionReportContainer::_internal_time_in_force() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::transport::TimeInForce>(_impl_.time_in_force_);
}
inline void ExecutionReportContainer::_internal_set_time_in_force(::transport::TimeInForce value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_in_force_ = value;
}

// double leaves_qty = 15;
inline bool ExecutionReportContainer::has_leaves_qty() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00002000U);
  return value;
}
inline void ExecutionReportContainer::clear_leaves_qty() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leaves_qty_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00002000U);
}
inline double ExecutionReportContainer::leaves_qty() const {
  // @@protoc_insertion_point(field_get:transport.ExecutionReportContainer.leaves_qty)
  return _internal_leaves_qty();
}
inline void ExecutionReportContainer::set_leaves_qty(double value) {
  _internal_set_leaves_qty(value);
  SetHasBit(_impl_._has_bits_[0], 0x00002000U);
  // @@protoc_insertion_point(field_set:transport.ExecutionReportContainer.leaves_qty)
}
inline double ExecutionReportContainer::_internal_leaves_qty() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.leaves_qty_;
}
inline void ExecutionReportContainer::_internal_set_leaves_qty(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leaves_qty_ = value;
}

// double cum_qty = 16;
inline bool ExecutionReportContainer::has_cum_qty() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00004000U);
  return value;
}
inline void ExecutionReportContainer::clear_cum_qty() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cum_qty_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00004000U);
}
inline double ExecutionReportContainer::cum_qty() const {
  // @@protoc_insertion_point(field_get:transport.ExecutionReportContainer.cum_qty)
  return _internal_cum_qty();
}
inline void ExecutionReportContainer::set_cum_qty(double value) {
  _internal_set_cum_qty(value);
  SetHasBit(_impl_._has_bits_[0], 0x00004000U);
  // @@protoc_insertion_point(field_set:transport.ExecutionReportContainer.cum_qty)
}
inline double ExecutionReportContainer::_internal_cum_qty() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cum_qty_;
}
inline void ExecutionReportContainer::_internal_set_cum_qty(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cum_qty_ = value;
}

// double avg_px = 17;
inline bool ExecutionReportContainer::has_avg_px() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00008000U);
  return value;
}
inline void ExecutionReportContainer::clear_avg_px() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.avg_px_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00008000U);
}
inline double ExecutionReportContainer::avg_px() const {
  // @@protoc_insertion_point(field_get:transport.ExecutionReportContainer.avg_px)
  return _internal_avg_px();
}
inline void ExecutionReportContainer::set_avg_px(double value) {
  _internal_set_avg_px(value);
  SetHasBit(_impl_._has_bits_[0], 0x00008000U);
  // @@protoc_insertion_point(field_set:transport.ExecutionReportContainer.avg_px)
}
inline double ExecutionReportContainer::_internal_avg_px() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.avg_px_;
}
inline void ExecutionReportContainer::_internal_set_avg_px(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.avg_px_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace transport


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::transport::OrderType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::transport::OrderType>() {
  return ::transport::OrderType_descriptor();
}
template <>
struct is_proto_enum<::transport::Side> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::transport::Side>() {
  return ::transport::Side_descriptor();
}
template <>
struct is_proto_enum<::transport::TimeInForce> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::transport::TimeInForce>() {
  return ::transport::TimeInForce_descriptor();
}
template <>
struct is_proto_enum<::transport::ExecTransType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::transport::ExecTransType>() {
  return ::transport::ExecTransType_descriptor();
}
template <>
struct is_proto_enum<::transport::ExecTypeOrOrderStatus> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::transport::ExecTypeOrOrderStatus>() {
  return ::transport::ExecTypeOrOrderStatus_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // containers_2eproto_2epb_2eh
