#pragma once

#include <boost/uuid/uuid.hpp>
#include <boost/uuid/uuid_generators.hpp>

namespace core::uuid {
/// a singleton class wrapping boost uuid generator
/// to avoid overhead when creating new generator instance
class UUIDGeneratorWrapper {
  public:
    static UUIDGeneratorWrapper& instance() {
        static UUIDGeneratorWrapper singleton{};
        return singleton;
    }

    void generate(char* out) const {
        format_uuid_canonical(generator()(), out);
    }

    UUIDGeneratorWrapper(const UUIDGeneratorWrapper&) = delete;
    UUIDGeneratorWrapper& operator=(const UUIDGeneratorWrapper&) = delete;
    UUIDGeneratorWrapper(UUIDGeneratorWrapper&&) = delete;
    UUIDGeneratorWrapper& operator=(UUIDGeneratorWrapper&&) = delete;

  private:
    UUIDGeneratorWrapper() = default;

    static boost::uuids::time_generator_v7& generator() {
        static thread_local boost::uuids::time_generator_v7 thread_local_generator;
        return thread_local_generator;
    }

    /// helper to convert the 16-byte uuid generated by boost library to
    /// xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx format 0x0F = 00001111 as a mask for lower 4 bits for each
    /// map each byte's upper & lower 4 bits to 0 - 15 (0 - 9, a - f) respectively
    static void format_uuid_canonical(const boost::uuids::uuid& id, char* out) {
        static constexpr char HEX_DIGITS[] = "0123456789abcdef";
        int out_idx = 0;
        for (int i = 0; i < 16; ++i) {
            if (i == 4 || i == 6 || i == 8 || i == 10) {
                out[out_idx++] = '-';
            }

            const unsigned char byte = id.data[i];
            out[out_idx++] = HEX_DIGITS[(byte >> 4) & 0x0F];
            out[out_idx++] = HEX_DIGITS[byte & 0x0F];
        }
        out[out_idx] = '\0';
    }
};

} // namespace core::uuid
